r"""Write the ``0/`` fields the AIAA 99-3455 cases need.

Separate from :mod:`plumetools.foamio.fields`, which reproduces the pre-refactor
output byte-for-byte -- irregular indentation and all -- because a regression
golden is pinned to it. This case family has no such freeze and different needs,
so it writes its own files rather than adding a second meaning to that module's
formatting quirks.

What is written
---------------

============================  =================  =====================================
file                          class              read by
============================  =================  =====================================
``boundaryU``                 volVectorField     the inflow model; ``MaxwellianThermal``
``boundaryT``                 volScalarField     the inflow model; ``MaxwellianThermal``
``boundaryNumberDensity_N2``  volScalarField     ``plumeFieldInflow`` (per face)
nine measurement fields       vol{Scalar,Vector} constructed by ``DSMCCloud``
============================  =================  =====================================

Three details are load-bearing:

``boundaryT`` is a **volScalarField**.
    Standard ``dsmcFoam`` declares it as one (``FreeStream.C``); the MNF fork
    takes a *vector* holding per-component translational temperature. Writing the
    wrong class is a hard read failure, not a silent mis-run.

``boundaryT`` and ``boundaryU`` must be set on the **wall** patches too.
    ``MaxwellianThermal`` reads the wall temperature from
    ``cloud.boundaryT()`` on the wall face (``MaxwellianThermal.C``), not from its
    own coefficients, and adds ``cloud.boundaryU()`` as the wall velocity. A
    ``zeroGradient`` there would evaluate to the zero internal field, giving
    reflected particles ``sqrt(k*0/m) = 0`` thermal speed -- they would leave the
    wall with only the wall's own velocity, which is zero, and stick.

``fD`` and ``q`` must be ``calculated`` on wall patches.
    ``DSMCParcel::hitWallPatch`` accumulates directly into their boundary fields.
    A ``zeroGradient`` patch field writes only ``type zeroGradient;`` with no
    values, so everything the solver measured on the wall would be discarded at
    write time -- and the surface pressure is exactly that data. OpenFOAM's own
    dsmcFoam tutorials ship ``calculated`` here for the same reason.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np

from plumetools.foamio.primitives import BANNER, SEPARATOR, write_lines

GENERATOR = "plumetools.markelov1999.foamfields"

#: Geometric patch types whose patchField type must match exactly. OpenFOAM
#: rejects anything else with "inconsistent patch and patchField types".
CONSTRAINT_PATCH_TYPES = frozenset({
    "symmetry", "symmetryPlane", "empty", "wedge", "cyclic", "cyclicAMI",
    "processor", "processorCyclic", "nonuniformTransformCyclic",
})

#: Fields ``DSMCCloud`` requires in ``0/`` but ``dsmcInitialise`` does not create.
#: ``(name, class, dimensions, uniform internal value, needs values on walls)``.
#:
#: The last flag marks the two fields ``DSMCParcel::hitWallPatch`` writes into
#: directly. They must be ``calculated`` on wall patches or the wall measurements
#: are lost at write time -- see the module docstring.
MEASUREMENT_FIELDS = (
    ("dsmcRhoN",  "volScalarField", "[0 -3 0 0 0 0 0]",  "0",       False),
    ("fD",        "volVectorField", "[1 -1 -2 0 0 0 0]", "(0 0 0)", True),
    ("iDof",      "volScalarField", "[0 -3 0 0 0 0 0]",  "0",       False),
    ("internalE", "volScalarField", "[1 -1 -2 0 0 0 0]", "0",       False),
    ("linearKE",  "volScalarField", "[1 -1 -2 0 0 0 0]", "0",       False),
    ("momentum",  "volVectorField", "[1 -2 -1 0 0 0 0]", "(0 0 0)", False),
    ("q",         "volScalarField", "[1 0 -3 0 0 0 0]",  "0",       True),
    ("rhoM",      "volScalarField", "[1 -3 0 0 0 0 0]",  "0",       False),
    ("rhoN",      "volScalarField", "[0 -3 0 0 0 0 0]",  "0",       False),
)


def _header(field_class: str, object_name: str, note: str) -> list[str]:
    return [
        BANNER,
        f"// GENERATED by {GENERATOR} from case.yaml -- do not edit.",
        "// Regenerate with ./Allrun.",
        f"// {note}",
        "FoamFile",
        "{",
        "    version     2.0;",
        "    format      ascii;",
        f"    class       {field_class};",
        '    location    "0";',
        f"    object      {object_name};",
        "}",
        SEPARATOR,
        "",
    ]


def patch_field_type(geometric_type: str) -> str:
    """The patchField type a given geometric patch type requires.

    Constraint patches must carry a patchField of their own name; OpenFOAM fails
    with "inconsistent patch and patchField types" otherwise.
    """
    return geometric_type if geometric_type in CONSTRAINT_PATCH_TYPES else "zeroGradient"


def _nonuniform_entry(patch: str, list_type: str, values) -> list[str]:
    values = list(values)
    return [
        f"    {patch}",
        "    {",
        "        type            fixedValue;",
        f"        value           nonuniform List<{list_type}>",
        f"        {len(values)}",
        "        (",
        *values,
        "        );",
        "    }",
    ]


def _uniform_entry(patch: str, bc_type: str, value: str | None) -> list[str]:
    lines = [f"    {patch}", "    {", f"        type            {bc_type};"]
    if value is not None:
        lines.append(f"        value           uniform {value};")
    lines.append("    }")
    return lines


def _write_field(path: Path, field_class: str, name: str, dimensions: str,
                 internal: str, entries: list[str], note: str) -> Path:
    return write_lines(path, [
        *_header(field_class, name, note),
        f"dimensions      {dimensions};",
        f"internalField   uniform {internal};",
        "boundaryField",
        "{",
        *entries,
        "}",
        "",
        "// ************************************************************************* //",
    ])


def _wall_and_open_patches(patches, cfg):
    """Split the mesh's patches into (inflow, walls, constraint, open) by name."""
    names = cfg.mesh.patch_names
    inflow = names.get("inflow", "inflow")
    walls = {names.get("cylinder", "cylinder"), names.get("plate", "plate")}
    return inflow, walls


def write_inflow_fields(case_dir: Path, inflow, cfg, patches) -> list[Path]:
    """Write ``boundaryU``, ``boundaryT`` and ``boundaryNumberDensity_<species>``.

    Args:
        case_dir: the case directory; ``0/`` is created under it.
        inflow: a :class:`plumetools.markelov1999.inflow.InflowResult`.
        cfg: the case config.
        patches: the mesh's patches, as
            :func:`plumetools.mesh.read_boundary` returns.

    Returns:
        The paths written.

    Raises:
        ValueError: if the inflow patch is not in the mesh, or if a face count
            disagrees with the patch. Writing a list of the wrong length is
            accepted by neither OpenFOAM nor debugging.
    """
    out = Path(case_dir) / "0"
    inflow_patch, wall_patches = _wall_and_open_patches(patches, cfg)

    if inflow_patch not in patches:
        raise ValueError(
            f"inflow patch {inflow_patch!r} is not in the mesh; "
            f"available: {sorted(patches)}")
    declared = patches[inflow_patch].n_faces
    if declared != inflow.n_faces:
        raise ValueError(
            f"the model produced {inflow.n_faces} face values but patch "
            f"{inflow_patch!r} declares {declared} faces")

    species = cfg.dsmc.species.name
    wall_T = float(cfg.dsmc.wall_temperature_K)
    written: list[Path] = []

    def other_entries(kind: str) -> list[str]:
        """Patch entries for everything except the inflow patch.

        ``kind`` selects the value written on a wall: ``"T"`` gives the wall
        temperature, ``"U"`` a zero wall velocity, ``"n"`` a zero density.
        """
        entries: list[str] = []
        for name, info in patches.items():
            if name == inflow_patch:
                continue
            constraint = patch_field_type(info.type)
            if constraint != "zeroGradient":
                entries.extend(_uniform_entry(name, constraint, None))
            elif name in wall_patches and kind == "T":
                # MaxwellianThermal reads the wall temperature from HERE.
                entries.extend(_uniform_entry(name, "fixedValue", f"{wall_T:g}"))
            elif name in wall_patches and kind == "U":
                entries.extend(_uniform_entry(name, "fixedValue", "(0 0 0)"))
            elif name in wall_patches:
                entries.extend(_uniform_entry(name, "fixedValue", "0"))
            else:
                entries.extend(_uniform_entry(name, "zeroGradient", None))
        return entries

    u_rows = [f"            ({u:.10g} {v:.10g} {w:.10g})" for u, v, w in inflow.U]
    written.append(_write_field(
        out / "boundaryU", "volVectorField", "boundaryU", "[0 1 -1 0 0 0 0]",
        "(0 0 0)",
        _nonuniform_entry(inflow_patch, "vector", u_rows) + other_entries("U"),
        f"Source-flow velocity, radial with |U| = {inflow.v_limit:.6g} m/s. "
        f"Walls carry a zero velocity, which MaxwellianThermal adds to the "
        f"reflected particle."))

    t_rows = [f"            {t:.10g}" for t in inflow.T]
    written.append(_write_field(
        out / "boundaryT", "volScalarField", "boundaryT", "[0 0 0 1 0 0 0]", "0",
        _nonuniform_entry(inflow_patch, "scalar", t_rows) + other_entries("T"),
        f"volScalarField -- standard dsmcFoam, NOT the MNF fork's vector form. "
        f"Walls carry {wall_T:g} K, which is where MaxwellianThermal reads the "
        f"wall temperature from."))

    n_rows = [f"            {n:.10g}" for n in inflow.rhoN]
    written.append(_write_field(
        out / f"boundaryNumberDensity_{species}", "volScalarField",
        f"boundaryNumberDensity_{species}", "[0 -3 0 0 0 0 0]", "0",
        _nonuniform_entry(inflow_patch, "scalar", n_rows) + other_entries("n"),
        f"Per-face number density, read by plumeFieldInflow. Stock FreeStream "
        f"has no field form and would collapse this to one scalar."))

    return written


def write_measurement_fields(case_dir: Path, patches) -> list[Path]:
    """Write the nine zeroed fields ``DSMCCloud`` constructs itself from.

    Args:
        case_dir: the case directory; ``0/`` is created under it.
        patches: the mesh's patches, name to
            :class:`plumetools.mesh.boundary.PatchInfo`.

    Returns:
        The paths written.

    ``dsmcFoam`` aborts with ``cannot find file "0/q"`` and so on if any is
    absent, and ``dsmcInitialise`` does not create them -- OpenFOAM's tutorials
    ship them in ``0.orig`` and copy them in.

    Generated rather than shipped so the boundary entries name the patches this
    mesh actually has. A checked-in ``0.orig`` would hard-code a patch list, which
    is finding AD-03 in the legacy lineage.
    """
    out = Path(case_dir) / "0"
    written = []

    for name, field_class, dimensions, zero, wall_values in MEASUREMENT_FIELDS:
        entries: list[str] = []
        for patch_name, info in patches.items():
            bc = patch_field_type(info.type)
            if bc != "zeroGradient":
                entries.extend(_uniform_entry(patch_name, bc, None))
            elif wall_values and info.type == "wall":
                # DSMCParcel::hitWallPatch writes into this field's boundary
                # values. zeroGradient writes no values at all, so the wall
                # measurement -- which is the result -- would be discarded.
                entries.extend(_uniform_entry(patch_name, "calculated", zero))
            else:
                entries.extend(_uniform_entry(patch_name, bc, None))

        note = ("Zeroed measurement field required by DSMCCloud."
                + ("  'calculated' on walls: DSMCParcel::hitWallPatch writes here, "
                   "and zeroGradient would discard it at write time."
                   if wall_values else ""))
        written.append(_write_field(
            out / name, field_class, name, dimensions, zero, entries, note))

    return written


def write_all(case_dir: Path, inflow, cfg, patches) -> list[Path]:
    """Write every ``0/`` field this case family needs."""
    return (write_inflow_fields(case_dir, inflow, cfg, patches)
            + write_measurement_fields(case_dir, patches))


def read_patch_field(path: Path, patch: str) -> np.ndarray:
    """Read one patch's values out of an OpenFOAM field file.

    Args:
        path: the field file, e.g. ``<case>/0.004/fDMean``.
        patch: the patch name to extract.

    Returns:
        ``(n,)`` for a scalar field or ``(n, 3)`` for a vector field. A
        ``uniform`` entry is expanded to a one-element array; the caller knows
        the face count and can broadcast.

    Raises:
        FileNotFoundError: if the file is absent.
        ValueError: if the patch is missing, or has no ``value`` entry -- which is
            what a ``zeroGradient`` boundary condition looks like on disk, and
            means the data was never written rather than that it was zero.

    A small purpose-built parser rather than a general dictionary reader: it needs
    to survive nested braces inside the target patch entry, which is what the
    legacy line-offset parsers could not do (findings RB-03, RB-04).
    """
    import re

    path = Path(path)
    if not path.is_file():
        raise FileNotFoundError(f"no field file at {path}")
    text = path.read_text(encoding="utf-8", errors="replace")

    start = text.find("boundaryField")
    if start < 0:
        raise ValueError(f"{path}: no boundaryField block")

    # Find the patch entry, then take the balanced brace block that follows.
    match = re.search(rf"^\s*{re.escape(patch)}\s*$", text[start:], re.M)
    if not match:
        raise ValueError(f"{path}: patch {patch!r} is not in the boundaryField")

    body_start = text.index("{", start + match.end())
    depth, i = 0, body_start
    while i < len(text):
        if text[i] == "{":
            depth += 1
        elif text[i] == "}":
            depth -= 1
            if depth == 0:
                break
        i += 1
    body = text[body_start + 1:i]

    nonuniform = re.search(
        r"value\s+nonuniform\s+List<(\w+)>\s*(\d+)?\s*\((.*?)\)\s*;", body, re.S)
    if nonuniform:
        kind, _count, payload = nonuniform.groups()
        numbers = [float(v) for v in re.findall(r"[-+0-9.eE]+", payload)]
        arr = np.asarray(numbers, dtype=np.float64)
        return arr.reshape(-1, 3) if kind == "vector" else arr

    uniform = re.search(r"value\s+uniform\s+(\([^)]*\)|[-+0-9.eE]+)\s*;", body)
    if uniform:
        token = uniform.group(1)
        if token.startswith("("):
            return np.asarray(
                [[float(v) for v in re.findall(r"[-+0-9.eE]+", token)]],
                dtype=np.float64)
        return np.asarray([float(token)], dtype=np.float64)

    raise ValueError(
        f"{path}: patch {patch!r} has no 'value' entry. A zeroGradient boundary "
        f"condition writes none, which means the solver's data for this patch was "
        f"discarded at write time rather than being zero -- see "
        f"plumetools.markelov1999.foamfields for why fD and q must be 'calculated' "
        f"on walls."
    )
