r"""Generate ``constant/dsmcProperties``, ``system/controlDict`` and friends.

Requirement 2 of the case specification asks that physical values live in **one
authoritative configuration source**. That source is ``case.yaml``, so these
dictionaries are *generated* from it rather than shipped and patched.

The alternative -- shipping them and editing with string substitution, the way
``util/caseFoam/genCases.py`` does -- makes the same number exist in two places
and depends on the exact spacing of a line that nothing enforces::

    'system/controlDict': {'#!stringManipulation':
                            {'deltaT          1.0E-05': '%s' % deltaT}}

That silently does nothing if the shipped file is reformatted, if the value is
already different, or if a case was generated from a slightly older base. None of
those is detectable from the output.

What is generated
-----------------

========================================  =============================================
``constant/dsmcProperties``               species, VHS/LB models, particle weight,
                                          the inflow model and its coefficients
``system/controlDict``                    times, writing, ``libs``, ``fieldAverage``
``system/dsmcInitialiseDict``             the near-vacuum initial fill
``system/decomposeParDict``               subdomain count
``system/fvSchemes`` / ``fvSolution``     required by ``fvMesh``, unused by DSMC
========================================  =============================================
"""

from __future__ import annotations

from pathlib import Path

from plumetools.foamio.primitives import BANNER, SEPARATOR, write_lines

GENERATOR = "plumetools.markelov1999.foamdicts"

#: The shared library that provides ``plumeFieldInflow``.
PLUME_LIB = "libplumeDsmcBoundaryModels.so"


def _header(object_name: str, note: str, location: str | None = None) -> list[str]:
    lines = [
        BANNER,
        f"// GENERATED by {GENERATOR} from case.yaml -- do not edit.",
        "// Regenerate with ./Allmesh. case.yaml is the authoritative source.",
        f"// {note}",
        "FoamFile",
        "{",
        "    version     2.0;",
        "    format      ascii;",
        "    class       dictionary;",
    ]
    if location:
        lines.append(f'    location    "{location}";')
    lines += [f"    object      {object_name};", "}", SEPARATOR, ""]
    return lines


def _footer() -> list[str]:
    return ["", "// ************************************************************************* //"]


def render_dsmc_properties(cfg, n_equivalent_particles: float,
                           number_density_field: str | None = None) -> str:
    """``constant/dsmcProperties``.

    Args:
        cfg: the case config.
        n_equivalent_particles: the particle weight to write. Passed rather than
            read from ``cfg`` so the caller must have resolved it -- a ``null``
            in ``case.yaml`` means "derive", and deriving it silently here would
            hide which number was actually used.
        number_density_field: the field ``plumeFieldInflow`` reads. Defaults to
            ``boundaryNumberDensity_<species>``.

    Returns:
        The dictionary text.

    Raises:
        ValueError: for a non-positive weight, or an inflow model this generator
            does not know how to write coefficients for.
    """
    if not n_equivalent_particles > 0:
        raise ValueError(
            f"nEquivalentParticles must be positive, got {n_equivalent_particles}")

    d = cfg.dsmc
    sp = d.species
    from plumetools.markelov1999.inflow import molecular_mass_from_config
    mass = molecular_mass_from_config(cfg)
    field = number_density_field or f"boundaryNumberDensity_{sp.name}"

    lines = _header(
        "dsmcProperties",
        f"N2, VHS + Larsen-Borgnakke, ZR = {d.rotational_collision_number:g}.",
        location="constant")

    lines += [
        "// General Properties",
        "// ~~~~~~~~~~~~~~~~~~",
        "",
        "// The uniform particle weight. Standard dsmcFoam has ONE weight for the",
        "// whole domain -- DSMCCloud::nParticle_ is a single scalar -- so there is",
        "// no radial or adaptive weighting to configure. Chosen so the",
        f"// '{cfg.resolution.sizing_region}' region reaches",
        f"// {cfg.resolution.target_particles_per_cell:g} particles per cell; the",
        "// occupancy that implies elsewhere is reported by",
        "// plumetools.markelov1999.resolution, not assumed.",
        f"nEquivalentParticles            {n_equivalent_particles:.6e};",
        "",
        "",
        "// Wall Interaction Model",
        "// ~~~~~~~~~~~~~~~~~~~~~~",
        "",
        f"// {d.wall_interaction_model} reads the wall temperature from",
        "// cloud.boundaryT() on the wall face, NOT from coefficients here.",
        f"// 0/boundaryT carries {d.wall_temperature_K:g} K on the cylinder and plate.",
        f"WallInteractionModel            {d.wall_interaction_model};",
        "",
        "",
        "// Binary Collision Model",
        "// ~~~~~~~~~~~~~~~~~~~~~~",
        "",
        "// [PAPER] VHS collisions with Larsen-Borgnakke internal-energy",
        "// redistribution. relaxationCollisionNumber is ZR.",
        f"BinaryCollisionModel            {d.binary_collision_model};",
        "",
        f"{d.binary_collision_model}Coeffs",
        "{",
        f"    Tref                        {d.t_ref_K:g};",
        f"    relaxationCollisionNumber   {d.rotational_collision_number:g};",
        "}",
        "",
        "",
        "// Inflow Boundary Model",
        "// ~~~~~~~~~~~~~~~~~~~~~",
        "",
    ]

    model = cfg.output.inflow_model
    if model == "plumeFieldInflow":
        lines += [
            "// applications/dsmcBoundaryModels/plumeFieldInflow. Two things stock",
            "// FreeStream cannot do: inject across a NAMED patch list, and read the",
            "// number density PER FACE.",
            "//",
            "// The library is loaded by system/controlDict's libs() entry. If it is",
            "// not compiled the run stops with an unknown-model error -- it never",
            "// falls back to uniform inflow.",
            f"InflowBoundaryModel             {model};",
            "",
            f"{model}Coeffs",
            "{",
            f"    patches ( {cfg.mesh.patch_names.get('inflow', 'inflow')} );",
            "",
            "    numberDensityFields",
            "    {",
            f"        {sp.name}    {field};",
            "    }",
            "}",
        ]
    elif model == "FreeStream":
        raise ValueError(
            "output.inflow_model 'FreeStream' cannot express this case: it takes "
            "one number density per species and injects across every patch-type "
            "boundary. Writing FreeStreamCoeffs here would produce a case that "
            "runs and is wrong. Use 'plumeFieldInflow'."
        )
    else:
        raise ValueError(
            f"this generator does not know how to write coefficients for "
            f"output.inflow_model {model!r}")

    lines += [
        "",
        "",
        "// Molecular species",
        "// ~~~~~~~~~~~~~~~~~",
        "",
        f"typeIdList                      ({sp.name});",
        "",
        "moleculeProperties",
        "{",
        f"    {sp.name}",
        "    {",
        f"        // mass = M / (1000 * N_A) with M = {sp.molar_mass_g_per_mol} g/mol.",
        "        // Derived rather than taken from the tutorial's rounded value, so",
        "        // the analytical source-flow model and the solver use one m.",
        f"        mass                            {mass:.9e};",
        "        // [ASSUMPTION] VHS coefficients the paper does not print.",
        f"        // Source: {sp.source}",
        f"        diameter                        {sp.diameter_m:g};",
        f"        internalDegreesOfFreedom        {int(sp.internal_degrees_of_freedom)};",
        f"        omega                           {sp.omega:g};",
        "    }",
        "}",
    ]
    lines += _footer()
    return "\n".join(lines) + "\n"


def render_control_dict(cfg) -> str:
    """``system/controlDict``, including ``libs`` and the ``fieldAverage`` block.

    The ``fieldAverage`` function object is not optional decoration. ``fD`` is
    reset every timestep by ``DSMCCloud::resetFields`` and re-accumulated by
    ``hitWallPatch``, so a written snapshot is a single-step momentum tally --
    far too noisy to read as a surface pressure. ``fDMean`` is what the
    post-processing measures.
    """
    d = cfg.dsmc
    lines = _header(
        "controlDict",
        f"dsmcFoam, deltaT {d.delta_t_s:g} s to {d.end_time_s:g} s, averaging from "
        f"{d.average_start_s:g} s.",
        location="system")

    lines += [
        "application     dsmcFoam;",
        "",
        "// The custom inflow boundary model. Build it with",
        "//     applications/dsmcBoundaryModels/Allwmake",
        "// Without this line dsmcFoam reports plumeFieldInflow as an unknown",
        "// InflowBoundaryModel and stops, which is the intended failure: there is",
        "// no silent fallback to a uniform inflow.",
        f'libs            ( "{PLUME_LIB}" );',
        "",
        "startFrom       startTime;",
        "startTime       0;",
        "stopAt          endTime;",
        f"endTime         {d.end_time_s:g};",
        f"deltaT          {d.delta_t_s:g};",
        "",
        "writeControl    runTime;",
        f"writeInterval   {d.write_interval_s:g};",
        "purgeWrite      0;",
        "writeFormat     ascii;",
        "writePrecision  10;",
        "writeCompression off;",
        "timeFormat      general;",
        "timePrecision   6;",
        "runTimeModifiable true;",
        "adjustTimeStep  no;",
        "",
        "functions",
        "{",
        "    fieldAverage1",
        "    {",
        "        type            fieldAverage;",
        "        libs            (fieldFunctionObjects);",
        "        writeControl    writeTime;",
        "        // Everything before this is treated as transient and discarded.",
        f"        timeStart       {d.average_start_s:g};",
        "",
        "        fields",
        "        (",
    ]
    # fD first: it is the one the results depend on.
    for name in ("fD", "q", "rhoN", "rhoM", "dsmcRhoN", "linearKE", "internalE",
                 "momentum", "iDof"):
        lines += [
            f"            {name}",
            "            {",
            "                mean        on;",
            "                prime2Mean  off;",
            "                base        time;",
            "            }",
        ]
    lines += [
        "        );",
        "    }",
        "}",
    ]
    lines += _footer()
    return "\n".join(lines) + "\n"


def render_dsmc_initialise_dict(cfg) -> str:
    """``system/dsmcInitialiseDict``.

    A near-vacuum fill, not a physical initial state: the domain starts
    essentially empty and the plume fills it from the inflow boundary. The value
    is small enough that the transient is short and large enough that the cloud
    is not constructed from zero particles.
    """
    d = cfg.dsmc
    lines = _header(
        "dsmcInitialiseDict",
        f"Near-vacuum seed: {d.initial_number_density_per_m3:g} 1/m^3 at rest.",
        location="system")
    lines += [
        "numberDensities",
        "{",
        f"    {d.species.name}          {d.initial_number_density_per_m3:g};",
        "};",
        "",
        f"temperature     {d.initial_temperature_K:g};",
        "",
        "// At rest: the plume arrives through the inflow boundary, it is not",
        "// already streaming when the run starts.",
        "velocity        (0 0 0);",
    ]
    lines += _footer()
    return "\n".join(lines) + "\n"


def render_decompose_par_dict(cfg) -> str:
    """``system/decomposeParDict``.

    ``scotch``: the mesh is unstructured after snappyHexMesh, and a geometric
    decomposition would cut the refined region badly. DSMC load balance follows
    particle count rather than cell count, so no decomposition is ideal here --
    ``scotch`` is simply the least bad default and the case runs correctly, if
    unevenly, under any of them.
    """
    lines = _header("decomposeParDict",
                    f"{cfg.dsmc.n_subdomains} subdomains, scotch.",
                    location="system")
    lines += [
        f"numberOfSubdomains  {int(cfg.dsmc.n_subdomains)};",
        "",
        "method              scotch;",
    ]
    lines += _footer()
    return "\n".join(lines) + "\n"


def render_fv_schemes() -> str:
    """``system/fvSchemes``. Required by ``fvMesh``; DSMC solves no PDE."""
    lines = _header("fvSchemes",
                    "Empty: dsmcFoam solves no field equations, but fvMesh "
                    "requires the file.", location="system")
    lines += [
        "ddtSchemes      { default none; }",
        "gradSchemes     { default none; }",
        "divSchemes      { default none; }",
        "laplacianSchemes { default none; }",
        "interpolationSchemes { default none; }",
        "snGradSchemes   { default none; }",
    ]
    lines += _footer()
    return "\n".join(lines) + "\n"


def render_fv_solution() -> str:
    """``system/fvSolution``. Required by ``fvMesh``; DSMC solves no PDE."""
    lines = _header("fvSolution",
                    "Empty: dsmcFoam solves no linear systems, but fvMesh "
                    "requires the file.", location="system")
    lines += ["solvers         { }"]
    lines += _footer()
    return "\n".join(lines) + "\n"


def write_case_dictionaries(case_dir: Path, cfg,
                            n_equivalent_particles: float) -> list[Path]:
    """Write every generated OpenFOAM dictionary for a case.

    Args:
        case_dir: the case directory.
        cfg: the case config.
        n_equivalent_particles: the resolved particle weight.

    Returns:
        The paths written.
    """
    case_dir = Path(case_dir)
    system = case_dir / "system"
    constant = case_dir / "constant"

    return [
        write_lines(constant / "dsmcProperties",
                    render_dsmc_properties(cfg, n_equivalent_particles).splitlines()),
        write_lines(system / "controlDict", render_control_dict(cfg).splitlines()),
        write_lines(system / "dsmcInitialiseDict",
                    render_dsmc_initialise_dict(cfg).splitlines()),
        write_lines(system / "decomposeParDict",
                    render_decompose_par_dict(cfg).splitlines()),
        write_lines(system / "fvSchemes", render_fv_schemes().splitlines()),
        write_lines(system / "fvSolution", render_fv_solution().splitlines()),
    ]
