r"""Generate ``constant/dsmcProperties``, ``system/controlDict`` and friends.

``case.yaml`` is the one authoritative source of physical inputs, so these are
**generated** from it rather than shipped and patched. The alternative -- string
substitution into a checked-in dictionary, the way ``util/caseFoam/genCases.py``
does it -- silently does nothing if the file is reformatted, if the value is
already different, or if the case came from an older template, and none of those
is visible in the output.

What is generated
-----------------

========================================  =====================================
``constant/dsmcProperties``               species, VHS, particle weight, the
                                          inflow model and its patch list
``system/controlDict``                    times, writing, ``libs``,
                                          ``fieldAverage``
``system/dsmcInitialiseDict``             the near-vacuum initial fill
``system/decomposeParDict``               subdomain count
``system/fvSchemes`` / ``fvSolution``     required by ``fvMesh``, unused by DSMC
========================================  =====================================

On NTC
------
Cai states "no-time-counter". There is no setting for it: NTC is the only
collision-selection algorithm ``DSMCCloud::collisions()`` implements in standard
``dsmcFoam``, so the requirement is met by construction and there is nothing to
write. That is recorded in ``docs/cai2012-case.md`` rather than left as an
unexplained absence.

On collisions at Kn = 100
-------------------------
They stay **on**. A ``NoBinaryCollision`` model exists and would make the
``Kn = 100`` case reproduce the collisionless solution by fiat, which proves
nothing. The validation claim is that DSMC *approaches* the collisionless
solution as the density falls, and that claim requires the collision machinery to
be running and finding almost nothing to do.
"""

from __future__ import annotations

from pathlib import Path

from plumetools.foamio.primitives import BANNER, SEPARATOR, write_lines

GENERATOR = "plumetools.cai2012.dictionaries"

#: The shared library that provides ``plumeFieldInflow``.
PLUME_LIB = "libplumeDsmcBoundaryModels.so"

#: Fields ``fieldAverage`` accumulates. ``rhoN`` first: the validation is a
#: density comparison, and a single-timestep ``rhoN`` is a one-step tally far too
#: noisy to compare with an analytical curve.
AVERAGED_FIELDS = ("rhoN", "rhoM", "dsmcRhoN", "momentum", "linearKE",
                   "internalE", "iDof", "fD", "q")


def _header(object_name: str, note: str, location: str | None = None) -> list[str]:
    lines = [
        BANNER,
        f"// GENERATED by {GENERATOR} from case.yaml -- do not edit.",
        "// Regenerate with ./Allmesh. case.yaml is the authoritative source.",
        f"// {note}",
        "FoamFile",
        "{",
        "    version     2.0;",
        "    format      ascii;",
        "    class       dictionary;",
    ]
    if location:
        lines.append(f'    location    "{location}";')
    lines += [f"    object      {object_name};", "}", SEPARATOR, ""]
    return lines


def _footer() -> list[str]:
    return ["",
            "// ************************************************************************* //"]


def render_dsmc_properties(cfg, exit_state, run) -> str:
    """``constant/dsmcProperties``.

    Args:
        cfg: the case config.
        exit_state: the :class:`~plumetools.cai2012.inflow.ExitState`.
        run: the :class:`~plumetools.cai2012.inflow.RunSettings`, for the weight.

    Returns:
        The dictionary text.

    Raises:
        ValueError: for a non-positive particle weight.
    """
    weight = float(run.n_equivalent_particles)
    if not weight > 0.0:
        raise ValueError(f"nEquivalentParticles must be positive, got {weight}")

    g = cfg.gas
    species = g.species_name
    field = f"boundaryNumberDensity_{species}"
    collisions = bool(cfg.dsmc.collisions_enabled)
    model = "VariableHardSphere" if collisions else "NoBinaryCollision"

    lines = _header(
        "dsmcProperties",
        f"{species}, VHS, Kn = {exit_state.knudsen:g}, "
        f"n0 = {exit_state.number_density_per_m3:.6e} 1/m^3.",
        location="constant")

    lines += [
        "// General Properties",
        "// ~~~~~~~~~~~~~~~~~~",
        "",
        "// Standard dsmcFoam has ONE particle weight for the whole domain --",
        "// DSMCCloud::nParticle_ is a single scalar -- so the occupancy target",
        "// can be met in exactly one place. It is met at the EXIT CELL, the",
        f"// densest cell in the domain: {run.exit_particles_per_cell:.1f}"
        f" particles/cell against a",
        f"// target of {cfg.resolution.target_particles_per_cell:g}. What that"
        " implies downstream is reported by",
        "// plumetools.cai2012.checks, not assumed.",
        f"nEquivalentParticles            {weight:.6e};",
        "",
        "",
        "// Wall Interaction Model",
        "// ~~~~~~~~~~~~~~~~~~~~~~",
        "",
        "// This case has NO wall patches -- the nozzle injects and every other",
        "// boundary is open vacuum -- but DSMCCloud constructs the model",
        "// unconditionally, so one has to be named.",
        "WallInteractionModel            MaxwellianThermal;",
        "",
        "",
        "// Binary Collision Model",
        "// ~~~~~~~~~~~~~~~~~~~~~~",
        "",
    ]

    if collisions:
        lines += [
            "// [PAPER] Cai states Variable Hard Sphere collisions with the",
            "// no-time-counter selection. NTC is not a setting: it is the only",
            "// selection algorithm DSMCCloud::collisions() implements, so it is",
            "// satisfied by construction.",
            "//",
            "// Collisions stay ON at every Knudsen number, including Kn = 100.",
            "// Switching them off would make the collisionless comparison true",
            "// by definition instead of demonstrating that DSMC approaches it.",
            f"BinaryCollisionModel            {model};",
            "",
            f"{model}Coeffs",
            "{",
            f"    // The reference temperature the VHS diameter {g.diameter_m:g} m"
            " belongs to.",
            "    // The two are a pair: changing one without the other changes"
            " the gas.",
            f"    Tref                        {float(g.t_ref_K):g};",
            "}",
        ]
    else:
        lines += [
            "// COLLISIONLESS. dsmc.collisions_enabled is false, so this run",
            "// cannot be used as evidence that DSMC approaches the collisionless",
            "// solution -- it IS the collisionless solution.",
            f"BinaryCollisionModel            {model};",
            "",
            f"{model}Coeffs",
            "{",
            "}",
        ]

    lines += [
        "",
        "",
        "// Inflow Boundary Model",
        "// ~~~~~~~~~~~~~~~~~~~~~",
        "",
        "// applications/dsmcBoundaryModels/plumeFieldInflow. Two things stock",
        "// FreeStream cannot do: inject across a NAMED patch list, and read the",
        "// number density PER FACE.",
        "//",
        "// The first is what makes this case possible at all. FreeStream injects",
        "// on every patch-type boundary, so the five vacuum boundaries would",
        "// become inlets; the only way to stop that is to declare them walls,",
        "// which replaces the vacuum with a reflecting box.",
        "//",
        "// The library is loaded by system/controlDict's libs() entry. Without",
        "// it the run stops with an unknown-model error -- there is no fallback.",
        f"InflowBoundaryModel             {cfg.output.inflow_model};",
        "",
        f"{cfg.output.inflow_model}Coeffs",
        "{",
        f"    patches ( {cfg.mesh.patch_names['nozzle']} );",
        "",
        "    numberDensityFields",
        "    {",
        f"        {species}    {field};",
        "    }",
        "}",
        "",
        "",
        "// Molecular species",
        "// ~~~~~~~~~~~~~~~~~",
        "",
        f"typeIdList                      ({species});",
        "",
        "moleculeProperties",
        "{",
        f"    {species}",
        "    {",
        "        // [ASSUMPTION / existing repository model] The paper names the",
        "        // gas and the collision model but not the VHS coefficients.",
        "        // These are the values cases/3d-inflow already runs argon with.",
        f"        mass                            {float(g.mass_kg):g};",
        f"        diameter                        {float(g.diameter_m):g};",
        f"        internalDegreesOfFreedom        "
        f"{int(g.internal_degrees_of_freedom)};",
        f"        omega                           {float(g.omega):g};",
        "    }",
        "}",
    ]
    lines += _footer()
    return "\n".join(lines) + "\n"


def render_control_dict(cfg, run) -> str:
    """``system/controlDict``, including ``libs`` and ``fieldAverage``.

    ``fieldAverage`` is not decoration. ``DSMCCloud::resetFields`` zeroes the
    measurement fields every timestep and ``calculateFields`` refills them, so a
    written ``rhoN`` is one step's worth of parcels -- pure shot noise against an
    analytical curve. ``rhoNMean`` is what the post-processing reads.
    """
    lines = _header(
        "controlDict",
        f"dsmcFoam, deltaT {run.delta_t_s:g} s to {run.end_time_s:g} s "
        f"({run.n_steps} steps), averaging from {run.average_start_s:g} s.",
        location="system")

    lines += [
        "application     dsmcFoam;",
        "",
        "// The custom inflow boundary model. Build it with",
        "//     applications/dsmcBoundaryModels/Allwmake",
        "// Without this line dsmcFoam reports plumeFieldInflow as an unknown",
        "// InflowBoundaryModel and stops, which is the intended failure.",
        f'libs            ( "{PLUME_LIB}" );',
        "",
        "// 'latestTime', not 'startTime': re-running ./Allrun CONTINUES the case",
        "// from its newest time directory instead of restarting it. On a case",
        "// with no results this resolves to 0, so a fresh run is unaffected.",
        "//",
        "// The whole DSMC state is in each time directory -- lagrangian/dsmc/",
        "// holds the parcels, and fieldAverage's accumulators are in uniform/ --",
        "// so a resumed run continues both the flow and the averaging rather",
        "// than starting either again.",
        "//",
        "// purgeWrite 0 below is what makes this safe: no time directory is ever",
        "// deleted, so there is always something to resume from.",
        "startFrom       latestTime;",
        "startTime       0;",
        "stopAt          endTime;",
        f"endTime         {run.end_time_s:g};",
        "",
        f"// Courant {run.courant:.3f}: a molecule at U0 + 3 sigma crosses that",
        f"// fraction of the smallest cell per step. Cai's dt/t0 = 1 would be",
        f"// {run.cai_delta_t_s:g} s, i.e. Courant {run.cai_courant:.2f} on this",
        "// mesh -- see docs/cai2012-case.md.",
        f"deltaT          {run.delta_t_s:g};",
        "",
        "// 'timeStep', not 'runTime'. Time::operator++ computes the runTime",
        "// write index as (value - startTime)/writeInterval, and on a RESUME",
        "// startTime is the resume point -- so the schedule starts again there",
        "// and a resumed leg shorter than one interval writes NOTHING. The step",
        "// index is global instead: each time directory stores it in uniform/time",
        "// and it continues across restarts.",
        "//",
        f"// {run.write_interval_steps} steps = {run.write_interval_s:g} s. The end",
        f"// time is a whole number of these ({run.n_writes} of them), so there is",
        "// a write exactly AT endTime wherever the run was resumed from.",
        "writeControl    timeStep;",
        f"writeInterval   {run.write_interval_steps};",
        "// Never purge: a deleted time directory is one fewer place to resume",
        "// from, and ./Allclean is the only thing here that removes one.",
        "purgeWrite      0;",
        "writeFormat     ascii;",
        "writePrecision  10;",
        "writeCompression off;",
        "timeFormat      general;",
        "timePrecision   6;",
        "runTimeModifiable true;",
        "adjustTimeStep  no;",
        "",
        "functions",
        "{",
        "    fieldAverage1",
        "    {",
        "        type            fieldAverage;",
        "        libs            (fieldFunctionObjects);",
        "        writeControl    writeTime;",
        "        // Everything before this is transient and is discarded.",
        f"        timeStart       {run.average_start_s:g};",
        "",
        "        fields",
        "        (",
    ]
    for name in AVERAGED_FIELDS:
        lines += [
            f"            {name}",
            "            {",
            "                mean        on;",
            "                prime2Mean  off;",
            "                base        time;",
            "            }",
        ]
    lines += ["        );", "    }", "}"]
    lines += _footer()
    return "\n".join(lines) + "\n"


def render_dsmc_initialise_dict(cfg) -> str:
    """``system/dsmcInitialiseDict``: a near-vacuum fill, at rest.

    Not a physical initial state. The domain starts essentially empty and the
    plume fills it from the nozzle; the value only has to be small enough that
    the transient is short and non-zero so the cloud is not built from nothing.
    """
    d = cfg.dsmc
    lines = _header(
        "dsmcInitialiseDict",
        f"Near-vacuum seed: {d.initial_number_density_per_m3:g} 1/m^3 at rest.",
        location="system")
    lines += [
        "numberDensities",
        "{",
        f"    {cfg.gas.species_name}          {d.initial_number_density_per_m3:g};",
        "};",
        "",
        f"temperature     {d.initial_temperature_K:g};",
        "",
        "// At rest: the plume arrives through the nozzle, it is not already",
        "// streaming when the run starts.",
        "velocity        (0 0 0);",
    ]
    lines += _footer()
    return "\n".join(lines) + "\n"


def simple_split(n_subdomains: int) -> tuple:
    r"""Factor ``n`` into an ``(nx, ny, nz)`` split, preferring lateral cuts.

    Args:
        n_subdomains: the number of ranks.

    Returns:
        ``(nx, ny, nz)`` whose product is exactly ``n_subdomains``.

    Why not simply ``(n, 1, 1)``
    ----------------------------
    DSMC cost follows **parcels**, not cells, and on this mesh those are two very
    different distributions. Parcels per cell go as ``n * V``: the graded outer
    cells are ~170x the core cell in each direction, so even at a thousandth of
    the exit density they hold several times the parcels of a core cell -- and
    there are far more of them.

    ``simple`` gives every rank an equal number of **cells**, so a split along
    ``x`` alone hands the whole outer shell to the last rank. Measured on the
    ``Kn = 100`` case at ``(12 1 1)``: 320 000 parcels on rank 11 against ~44 000
    on ranks 0, 3 and 6 -- a 3x imbalance, and the run went at the speed of the
    slowest rank.

    Splitting the lateral directions cuts that shell up instead, so the factors
    are assigned to the axis with the smallest current count, taking ``y`` and
    ``z`` before ``x``. For 12 that gives ``(2 3 2)``; for 4, ``(1 2 2)`` -- no
    cut across the beam at all. On the same case and the same 12 ranks that
    measured 1.21 s per step at ``(12 1 1)``, ``(2 3 2)`` gives **0.48 s** -- a
    2.5x speedup for a changed tuple.

    This is still not a *particle* decomposition. Doing that properly needs a
    weighted method (``scotch`` with a ``weightField``) or OpenFOAM's runtime
    load balancing; neither is configured here. It is a throughput question, not
    a correctness one, and the improvement from a lateral split is most of what
    is available for no extra machinery.
    """
    n = int(n_subdomains)
    if n < 1:
        raise ValueError(f"n_subdomains must be >= 1, got {n_subdomains}")

    factors = []
    remainder = n
    divisor = 2
    while divisor * divisor <= remainder:
        while remainder % divisor == 0:
            factors.append(divisor)
            remainder //= divisor
        divisor += 1
    if remainder > 1:
        factors.append(remainder)
    factors.sort(reverse=True)

    # Index 0 is x. Preference order y, z, x on a tie, so a small rank count
    # never cuts across the beam.
    counts = [1, 1, 1]
    for factor in factors:
        order = (1, 2, 0)
        best = min(order, key=lambda axis: counts[axis])
        counts[best] *= factor
    return tuple(counts)


def render_decompose_par_dict(cfg) -> str:
    """``system/decomposeParDict``.

    ``simple``, split in all three directions by :func:`simple_split`. See that
    function for why ``(n 1 1)`` is the wrong shape for this mesh, and why
    ``scotch`` -- which balances cells -- would be no better.
    """
    n = int(cfg.dsmc.n_subdomains)
    nx, ny, nz = simple_split(n)
    lines = _header("decomposeParDict",
                    f"{n} subdomains, simple, split ({nx} {ny} {nz}).",
                    location="system")
    lines += [
        "// DSMC cost follows PARCELS, not cells, and 'simple' balances cells.",
        "// On this graded mesh the outer cells are ~170x the core cell in each",
        "// direction, so despite the low density out there they hold most of the",
        "// parcels -- and an (n 1 1) split hands that whole shell to one rank.",
        "// Measured at Kn = 100 with (12 1 1): 320 000 parcels on the last rank",
        "// against ~44 000 on the others. Splitting laterally cuts the shell up.",
        f"numberOfSubdomains  {n};",
        "",
        "method              simple;",
        "",
        "coeffs",
        "{",
        f"    n               ({nx} {ny} {nz});",
        "}",
    ]
    lines += _footer()
    return "\n".join(lines) + "\n"


def render_fv_schemes() -> str:
    """``system/fvSchemes``. Required by ``fvMesh``; DSMC solves no PDE."""
    lines = _header("fvSchemes",
                    "Empty: dsmcFoam solves no field equations, but fvMesh "
                    "requires the file.", location="system")
    lines += [
        "ddtSchemes      { default none; }",
        "gradSchemes     { default none; }",
        "divSchemes      { default none; }",
        "laplacianSchemes { default none; }",
        "interpolationSchemes { default none; }",
        "snGradSchemes   { default none; }",
    ]
    lines += _footer()
    return "\n".join(lines) + "\n"


def render_fv_solution() -> str:
    """``system/fvSolution``. Required by ``fvMesh``; DSMC solves no PDE."""
    lines = _header("fvSolution",
                    "Empty: dsmcFoam solves no linear systems, but fvMesh "
                    "requires the file.", location="system")
    lines += ["solvers         { }"]
    lines += _footer()
    return "\n".join(lines) + "\n"


def write_case_dictionaries(case_dir: Path, cfg, exit_state, run) -> list[Path]:
    """Write every generated OpenFOAM dictionary for a case.

    Returns:
        The paths written.
    """
    case_dir = Path(case_dir)
    system = case_dir / "system"
    constant = case_dir / "constant"

    return [
        write_lines(constant / "dsmcProperties",
                    render_dsmc_properties(cfg, exit_state, run).splitlines()),
        write_lines(system / "controlDict",
                    render_control_dict(cfg, run).splitlines()),
        write_lines(system / "dsmcInitialiseDict",
                    render_dsmc_initialise_dict(cfg).splitlines()),
        write_lines(system / "decomposeParDict",
                    render_decompose_par_dict(cfg).splitlines()),
        write_lines(system / "fvSchemes", render_fv_schemes().splitlines()),
        write_lines(system / "fvSolution", render_fv_solution().splitlines()),
    ]
