r"""The ``0/`` fields the Cai 2012 cases need.

============================  =================  ==================================
file                          class              read by
============================  =================  ==================================
``boundaryU``                 volVectorField     ``plumeFieldInflow``, ``DSMCCloud``
``boundaryT``                 volScalarField     ``plumeFieldInflow``, ``DSMCCloud``
``boundaryNumberDensity_Ar``  volScalarField     ``plumeFieldInflow`` (per face)
nine measurement fields       vol{Scalar,Vector} constructed by ``DSMCCloud``
============================  =================  ==================================

A separate writer from :mod:`plumetools.foamio.fields` and from
:mod:`plumetools.markelov1999.foamfields`. The first is pinned byte-for-byte to a
regression golden; the second writes wall temperatures and per-face source-flow
profiles that this case has neither of. §4 of the case specification asks for a
Cai-specific writer precisely so the frozen one is not disturbed.

Why the exit values are ``uniform``
-----------------------------------
Cai's exit condition **is** uniform: one :math:`n_0`, one :math:`U_0`, one
:math:`T_0` across the whole disk. ``plumeFieldInflow`` reads the number density
per face, so a ``nonuniform List<scalar>`` of a few thousand identical numbers
would be equally correct -- and would be several thousand lines of noise in which
a genuine variation could not be seen. The uniform entry is the honest
representation of a uniform boundary condition, and the per-face capability is
what makes it possible to write a *non*-uniform one later without touching the
solver.

Three details are load-bearing, all inherited from how ``dsmcFoam`` reads these:

``boundaryT`` is a **volScalarField**.
    Standard ``dsmcFoam`` declares it as one. The MNF fork takes a *vector* of
    per-component translational temperatures. Writing the wrong class is a hard
    read failure, which is the good outcome.

The nozzle entries must be ``fixedValue``, not ``zeroGradient``.
    ``zeroGradient`` evaluates to the internal field, which is zero here, and
    ``plumeFieldInflow`` aborts with "Zero boundary temperature on inflow patch".

The vacuum patches must **not** be ``fixedValue`` with a real temperature.
    They are not inflows -- ``plumeFieldInflow`` is given an explicit patch list
    and injects on the nozzle only -- so what they carry is irrelevant to the
    physics, and ``zeroGradient`` says that plainly.
"""

from __future__ import annotations

from pathlib import Path

from plumetools.foamio.primitives import BANNER, SEPARATOR, write_lines

GENERATOR = "plumetools.cai2012.foamfields"

#: Geometric patch types whose patchField type must match exactly. OpenFOAM
#: rejects anything else with "inconsistent patch and patchField types".
CONSTRAINT_PATCH_TYPES = frozenset({
    "symmetry", "symmetryPlane", "empty", "wedge", "cyclic", "cyclicAMI",
    "processor", "processorCyclic", "nonuniformTransformCyclic",
})

#: Fields ``DSMCCloud`` requires in ``0/`` but ``dsmcInitialise`` does not create.
#: ``(name, class, dimensions, uniform internal value, written by hitWallPatch)``.
#:
#: ``dsmcFoam`` aborts with ``cannot find file "0/q"`` and so on if any is absent.
#: They are generated rather than shipped in a ``0.orig`` so the boundary entries
#: name the patches *this* mesh has -- including ``nozzle``, which does not exist
#: until ``createPatch`` has run.
MEASUREMENT_FIELDS = (
    ("dsmcRhoN",  "volScalarField", "[0 -3 0 0 0 0 0]",  "0",       False),
    ("fD",        "volVectorField", "[1 -1 -2 0 0 0 0]", "(0 0 0)", True),
    ("iDof",      "volScalarField", "[0 -3 0 0 0 0 0]",  "0",       False),
    ("internalE", "volScalarField", "[1 -1 -2 0 0 0 0]", "0",       False),
    ("linearKE",  "volScalarField", "[1 -1 -2 0 0 0 0]", "0",       False),
    ("momentum",  "volVectorField", "[1 -2 -1 0 0 0 0]", "(0 0 0)", False),
    ("q",         "volScalarField", "[1 0 -3 0 0 0 0]",  "0",       True),
    ("rhoM",      "volScalarField", "[1 -3 0 0 0 0 0]",  "0",       False),
    ("rhoN",      "volScalarField", "[0 -3 0 0 0 0 0]",  "0",       False),
)


def patch_field_type(geometric_type: str) -> str:
    """The patchField type a given geometric patch type requires."""
    return geometric_type if geometric_type in CONSTRAINT_PATCH_TYPES else "zeroGradient"


def _header(field_class: str, object_name: str, note: str) -> list[str]:
    return [
        BANNER,
        f"// GENERATED by {GENERATOR} from case.yaml -- do not edit.",
        "// Regenerate with ./Allrun.",
        f"// {note}",
        "FoamFile",
        "{",
        "    version     2.0;",
        "    format      ascii;",
        f"    class       {field_class};",
        '    location    "0";',
        f"    object      {object_name};",
        "}",
        SEPARATOR,
        "",
    ]


def _uniform_entry(patch: str, bc_type: str, value: str | None) -> list[str]:
    lines = [f"    {patch}", "    {", f"        type            {bc_type};"]
    if value is not None:
        lines.append(f"        value           uniform {value};")
    lines.append("    }")
    return lines


def _write_field(path: Path, field_class: str, name: str, dimensions: str,
                 internal: str, entries: list[str], note: str) -> Path:
    return write_lines(path, [
        *_header(field_class, name, note),
        f"dimensions      {dimensions};",
        f"internalField   uniform {internal};",
        "boundaryField",
        "{",
        *entries,
        "}",
        "",
        "// ************************************************************************* //",
    ])


def _boundary_entries(patches, nozzle_patch: str, nozzle_value: str | None,
                      *, calculated_on_walls: bool = False,
                      wall_value: str = "0") -> list[str]:
    """Patch entries for one field: the nozzle fixed, everything else neutral."""
    entries: list[str] = []
    for name, info in patches.items():
        constraint = patch_field_type(info.type)
        if name == nozzle_patch and nozzle_value is not None:
            entries.extend(_uniform_entry(name, "fixedValue", nozzle_value))
        elif constraint != "zeroGradient":
            entries.extend(_uniform_entry(name, constraint, None))
        elif calculated_on_walls and info.type == "wall":
            # DSMCParcel::hitWallPatch accumulates into this field's boundary
            # values; zeroGradient writes none, so the measurement would be
            # discarded at write time. This case has no wall patches, but a
            # variant that adds one must not silently lose its surface data.
            entries.extend(_uniform_entry(name, "calculated", wall_value))
        else:
            entries.extend(_uniform_entry(name, "zeroGradient", None))
    return entries


def write_inflow_fields(case_dir: Path, cfg, exit_state, patches) -> list[Path]:
    """Write ``boundaryU``, ``boundaryT`` and ``boundaryNumberDensity_<species>``.

    Args:
        case_dir: the case directory; ``0/`` is created under it.
        cfg: the case config.
        exit_state: the :class:`~plumetools.cai2012.inflow.ExitState`.
        patches: the mesh's patches, as
            :func:`plumetools.mesh.read_boundary` returns them.

    Returns:
        The paths written.

    Raises:
        ValueError: if the nozzle patch is not in the mesh, or has no faces.
            Either means ``topoSet`` / ``createPatch`` did not run or selected
            nothing, and the case would then inject through a patch that is not
            there -- which ``plumeFieldInflow`` turns into a fatal error, but
            only after the mesh has been decomposed.
    """
    out = Path(case_dir) / "0"
    nozzle = cfg.mesh.patch_names["nozzle"]

    if nozzle not in patches:
        raise ValueError(
            f"the nozzle patch {nozzle!r} is not in the mesh; available: "
            f"{sorted(patches)}. It is created by topoSet + createPatch, not by "
            f"blockMesh -- run ./Allmesh.")
    if patches[nozzle].n_faces == 0:
        raise ValueError(
            f"the nozzle patch {nozzle!r} has zero faces, so nothing would ever "
            f"be injected. The topoSet selection found no x = 0 face inside "
            f"r <= {0.5 * cfg.nozzle.diameter_m:g} m; the core cell is probably "
            f"coarser than the nozzle.")

    species = cfg.gas.species_name
    n0 = exit_state.number_density_per_m3
    u0 = exit_state.velocity_m_per_s
    t0 = exit_state.T0_K
    written: list[Path] = []

    written.append(_write_field(
        out / "boundaryU", "volVectorField", "boundaryU", "[0 1 -1 0 0 0 0]",
        "(0 0 0)",
        _boundary_entries(patches, nozzle, f"({u0:.10g} 0 0)"),
        f"Exit drift velocity U0 = S0 sqrt(2 R T0) = {u0:.6g} m/s along +x, "
        f"uniform across the disk. [DERIVED from S0 = "
        f"{exit_state.speed_ratio:g}]"))

    written.append(_write_field(
        out / "boundaryT", "volScalarField", "boundaryT", "[0 0 0 1 0 0 0]", "0",
        _boundary_entries(patches, nozzle, f"{t0:.10g}"),
        f"Exit temperature T0 = {t0:g} K [ASSUMPTION]. volScalarField -- "
        f"standard dsmcFoam, NOT the MNF fork's vector form."))

    written.append(_write_field(
        out / f"boundaryNumberDensity_{species}", "volScalarField",
        f"boundaryNumberDensity_{species}", "[0 -3 0 0 0 0 0]", "0",
        _boundary_entries(patches, nozzle, f"{n0:.10g}"),
        f"Exit number density n0 = {n0:.6e} 1/m^3, [DERIVED] from Kn = "
        f"{exit_state.knudsen:g} via lambda0 = Kn D. Read per face by "
        f"plumeFieldInflow; stock FreeStream has no field form at all."))

    return written


def write_measurement_fields(case_dir: Path, patches) -> list[Path]:
    """Write the nine zeroed fields ``DSMCCloud`` constructs itself from."""
    out = Path(case_dir) / "0"
    written = []
    for name, field_class, dimensions, zero, wall_values in MEASUREMENT_FIELDS:
        entries = _boundary_entries(
            patches, nozzle_patch="", nozzle_value=None,
            calculated_on_walls=wall_values, wall_value=zero)
        note = ("Zeroed measurement field required by DSMCCloud."
                + ("  'calculated' on any wall patch: DSMCParcel::hitWallPatch "
                   "writes there and zeroGradient would discard it."
                   if wall_values else ""))
        written.append(_write_field(
            out / name, field_class, name, dimensions, zero, entries, note))
    return written


def write_all(case_dir: Path, cfg, exit_state, patches) -> list[Path]:
    """Write every ``0/`` field this case family needs."""
    return (write_inflow_fields(case_dir, cfg, exit_state, patches)
            + write_measurement_fields(case_dir, patches))
