r"""Reusable pieces of a blockMesh + snappyHexMesh setup.

Two case families in this repository build a mesh the same way: a plain Cartesian
box from ``blockMesh``, then ``snappyHexMesh`` carving analytic **searchable
primitives** out of it. :mod:`plumetools.foamio.snappy` does it for a single
hemispherical inflow cavity; :mod:`plumetools.markelov1999.mesh` does it for an
inflow hemisphere plus a cylinder and a plate.

The differences between them are the surface list, the patch layout and the
refinement levels -- not the dictionary syntax. So the syntax lives here once and
both compose it, rather than each carrying its own copy of the castellate/snap
boilerplate.

Why primitives rather than STL
------------------------------
A ``searchableSphere`` / ``searchableCylinder`` / ``searchableBox`` is analytic:
snappyHexMesh snaps to the true surface instead of to a triangulation of it, the
worst measured vertex deviation on the existing case is 8.3e-16 m (round-off),
and nothing outside the repository has to be generated, versioned or shipped. An
STL would give up all three.

Block ordering
--------------
:func:`render_box_block_mesh_dict` emits the canonical OpenFOAM box ordering, in
which the block's local axes are ``(x, y, z)`` in that order, so a
``(nx ny nz)`` division triple means what it reads as.

That is worth stating because the ordering this module replaced did **not** have
that property: its local ``x1`` ran along ``+y`` and its ``x3`` along ``+x``, so
the three division counts were applied to the wrong axes. It went unnoticed
because the only case using it has a cube-shaped domain with all three counts
equal. On a non-cubic domain it would have silently transposed the resolution.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

BANNER = """\
/*--------------------------------*- C++ -*----------------------------------*\\
| =========                 |                                                 |
| \\\\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox           |
|  \\\\    /   O peration     | Version:  v1706                                 |
|   \\\\  /    A nd           | Web:      www.OpenFOAM.com                      |
|    \\\\/     M anipulation  |                                                 |
\\*---------------------------------------------------------------------------*/"""

SEPARATOR = "// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //"

#: Face keys accepted by :func:`render_box_block_mesh_dict`, and the vertex
#: quadruple of each in the canonical ordering below. Wound so the normal points
#: out of the box, which is what OpenFOAM requires of a boundary face.
BOX_FACES = {
    "x_min": (0, 4, 7, 3),
    "x_max": (1, 2, 6, 5),
    "y_min": (0, 1, 5, 4),
    "y_max": (3, 7, 6, 2),
    "z_min": (0, 3, 2, 1),
    "z_max": (4, 5, 6, 7),
}


def fmt(value: float) -> str:
    """Format a length for an OpenFOAM dictionary: 10 significant figures.

    Enough that a 0.1 mm feature in a 1 m domain survives the round trip, short
    enough that the dictionaries stay readable.
    """
    return f"{value:.10g}"


def fmt_point(point) -> str:
    """Format an ``(x, y, z)`` triple as an OpenFOAM vector literal."""
    x, y, z = point
    return f"({fmt(x)} {fmt(y)} {fmt(z)})"


def header(object_name: str, generator: str, note: str) -> list[str]:
    """The ``FoamFile`` block, plus a provenance comment naming the generator.

    Args:
        object_name: the ``object`` entry, which must match the file name.
        generator: dotted module path that wrote the file, so a reader of a
            generated dictionary can find the code that produced it.
        note: one line describing what this particular dictionary does.
    """
    return [
        BANNER,
        f"// GENERATED by {generator} from case.yaml -- do not edit.",
        "// Regenerate with ./Allmesh.",
        f"// {note}",
        "FoamFile",
        "{",
        "    version     2.0;",
        "    format      ascii;",
        "    class       dictionary;",
        f"    object      {object_name};",
        "}",
        SEPARATOR,
        "",
    ]


def write_lines(path: Path, lines: list[str]) -> Path:
    """Write LF-terminated lines, creating the parent directory.

    ``newline="\\n"`` explicitly: OpenFOAM reads CRLF, but a dictionary whose line
    endings depend on which platform generated it makes every diff unreadable.
    """
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines) + "\n")
    return path


# --------------------------------------------------------------------------- #
# searchable surfaces
# --------------------------------------------------------------------------- #

@dataclass(frozen=True)
class SearchableSurface:
    """Base for the analytic surfaces snappyHexMesh can snap to.

    Attributes:
        name: the ``geometry`` entry name. snappyHexMesh names the patch it
            creates after this, so it *is* the patch name -- there is no separate
            place to set it.
        level: octree refinement level at this surface. The resulting cell size is
            ``background_cell_size / 2**level``.
        patch_type: the geometric type of the created patch, written into
            ``patchInfo``. This is load-bearing for DSMC:

            * ``patch`` -- particles crossing it are **deleted**
              (``particle::hitBoundaryFace`` falls through to
              ``td.keepParticle = false``). Correct for an inflow surface and for
              an open vacuum boundary.
            * ``wall`` -- ``DSMCParcel::hitWallPatch`` runs, which both records the
              surface fluxes (``fD``, ``q``, ``rhoN``...) and applies the
              ``WallInteractionModel``. Required for a solid body: a body declared
              as ``patch`` would absorb every particle that hit it and exert no
              force.
    """

    name: str
    level: int = 0
    patch_type: str = "patch"

    def geometry_lines(self) -> list[str]:
        """The body of this surface's ``geometry`` entry, indented four spaces."""
        raise NotImplementedError

    def validate(self) -> None:
        """Raise ``ValueError`` if the surface is degenerate."""
        if int(self.level) < 0:
            raise ValueError(
                f"{self.name}: refinement level must be >= 0, got {self.level}")

    def min_feature_size_m(self) -> float:
        """The thinnest dimension of the body [m].

        What the **refined** cell has to resolve: for a plate this is the
        thickness, and cells no smaller than it cannot represent the body as a
        solid with two distinct faces.
        """
        raise NotImplementedError

    def max_feature_size_m(self) -> float:
        """The largest dimension of the body [m].

        What the **background** cell has to be smaller than. A body smaller than
        one background cell in every direction can sit entirely inside that cell,
        never intersect a cell boundary, and so never get flagged for refinement.
        """
        raise NotImplementedError

    def refined_cell_size_m(self, background_cell_size_m: float) -> float:
        """Cell size at this surface [m]: the background halved once per level."""
        return float(background_cell_size_m) / 2 ** int(self.level)


@dataclass(frozen=True)
class SearchableSphere(SearchableSurface):
    """An analytic sphere.

    Attributes:
        centre: ``(x, y, z)`` [m].
        radius: [m].

    v1706 spells the key ``centre``; v2006+ accepts ``origin`` as well, so
    ``centre`` is written for the wider compatibility.
    """

    centre: tuple = (0.0, 0.0, 0.0)
    radius: float = 1.0

    def geometry_lines(self) -> list[str]:
        return [
            "        type    searchableSphere;",
            f"        centre  {fmt_point(self.centre)};",
            f"        radius  {fmt(self.radius)};",
        ]

    def validate(self) -> None:
        super().validate()
        if not self.radius > 0.0:
            raise ValueError(f"{self.name}: sphere radius must be positive, "
                             f"got {self.radius}")

    def min_feature_size_m(self) -> float:
        return float(self.radius)

    def max_feature_size_m(self) -> float:
        return 2.0 * float(self.radius)


@dataclass(frozen=True)
class SearchableCylinder(SearchableSurface):
    """An analytic finite cylinder, capped at both ends.

    Attributes:
        point1: centre of one end cap [m].
        point2: centre of the other end cap [m].
        radius: [m].

    Finite and capped is the point: the paper's cylinder has ends inside the
    domain, and a cylinder that ran to the boundary would remove the
    three-dimensional wake around them.
    """

    point1: tuple = (0.0, 0.0, 0.0)
    point2: tuple = (0.0, 0.0, 1.0)
    radius: float = 1.0

    def geometry_lines(self) -> list[str]:
        return [
            "        type    searchableCylinder;",
            f"        point1  {fmt_point(self.point1)};",
            f"        point2  {fmt_point(self.point2)};",
            f"        radius  {fmt(self.radius)};",
        ]

    def validate(self) -> None:
        super().validate()
        if not self.radius > 0.0:
            raise ValueError(f"{self.name}: cylinder radius must be positive, "
                             f"got {self.radius}")
        if self.length_m() <= 0.0:
            raise ValueError(f"{self.name}: cylinder end caps coincide")

    def length_m(self) -> float:
        """Distance between the two end-cap centres [m]."""
        return sum((b - a) ** 2 for a, b in zip(self.point1, self.point2)) ** 0.5

    def min_feature_size_m(self) -> float:
        return min(float(self.radius), self.length_m())

    def max_feature_size_m(self) -> float:
        return max(2.0 * float(self.radius), self.length_m())


@dataclass(frozen=True)
class SearchableBox(SearchableSurface):
    """An analytic axis-aligned box.

    Attributes:
        min: ``(x, y, z)`` of the low corner [m].
        max: ``(x, y, z)`` of the high corner [m].

    Used here for the flat plate. Its thinnest dimension is what
    :meth:`min_feature_size_m` reports, which for a plate is the thickness -- the
    dimension a background mesh is most likely to be unable to find.
    """

    min: tuple = (0.0, 0.0, 0.0)
    max: tuple = (1.0, 1.0, 1.0)

    def geometry_lines(self) -> list[str]:
        return [
            "        type    searchableBox;",
            f"        min     {fmt_point(self.min)};",
            f"        max     {fmt_point(self.max)};",
        ]

    def validate(self) -> None:
        super().validate()
        for axis, (lo, hi) in enumerate(zip(self.min, self.max)):
            if not hi > lo:
                raise ValueError(
                    f"{self.name}: box axis {'xyz'[axis]} is degenerate "
                    f"({lo} .. {hi}); a zero-thickness body cannot be meshed as a "
                    f"solid, and snappyHexMesh has no baffle mode configured here")

    def min_feature_size_m(self) -> float:
        return min(hi - lo for lo, hi in zip(self.min, self.max))

    def max_feature_size_m(self) -> float:
        return max(hi - lo for lo, hi in zip(self.min, self.max))


# --------------------------------------------------------------------------- #
# dictionary sections
# --------------------------------------------------------------------------- #

def render_geometry_block(surfaces) -> list[str]:
    """The ``geometry { ... }`` block for a list of searchable surfaces.

    Raises:
        ValueError: for a duplicate surface name -- which would silently drop one
            of them, since OpenFOAM dictionary keys are unique.
    """
    names = [s.name for s in surfaces]
    duplicates = sorted({n for n in names if names.count(n) > 1})
    if duplicates:
        raise ValueError(f"duplicate searchable surface name(s) {duplicates}")

    lines = ["geometry", "{"]
    for surface in surfaces:
        surface.validate()
        lines += [f"    {surface.name}", "    {", *surface.geometry_lines(), "    }"]
    lines.append("}")
    return lines


def render_refinement_surfaces_block(surfaces, indent: str = "    ") -> list[str]:
    """The ``refinementSurfaces { ... }`` block, one entry per surface."""
    lines = [f"{indent}refinementSurfaces", f"{indent}{{"]
    for surface in surfaces:
        level = int(surface.level)
        lines += [
            f"{indent}    {surface.name}",
            f"{indent}    {{",
            f"{indent}        level ({level} {level});",
            f"{indent}        patchInfo",
            f"{indent}        {{",
            f"{indent}            type {surface.patch_type};",
            f"{indent}        }}",
            f"{indent}    }}",
        ]
    lines += [f"{indent}}}"]
    return lines


#: Cells required across the thinnest dimension of a body for it to be meshed as
#: a solid rather than as a smeared obstruction.
MIN_CELLS_ACROSS_THINNEST_FEATURE = 2


def check_surfaces_are_resolvable(surfaces, background_cell_size_m: float) -> None:
    """Refuse a background and level combination that cannot mesh a surface.

    Args:
        surfaces: the searchable surfaces, each carrying its own ``level``.
        background_cell_size_m: the uniform background cell size [m].

    Raises:
        ValueError: naming the surface, the offending dimension and the level that
            would fix it.

    Two separate conditions, for two separate failure modes:

    **Finding it.** snappyHexMesh only refines cells that intersect a surface, so
    a body smaller than one background cell in *every* direction can sit entirely
    inside that cell and never be flagged. The background cell must therefore be
    smaller than the body's largest dimension. Note this is not the same as being
    smaller than its *smallest*: a plate 12.7 mm thick and 381 mm tall spans
    hundreds of background cells laterally and cannot be missed, however coarse
    the background is relative to its thickness.

    **Resolving it.** After refinement the cell size is
    ``background / 2**level``, and that has to fit across the body's thinnest
    dimension at least :data:`MIN_CELLS_ACROSS_THINNEST_FEATURE` times. Below
    that, a plate has no interior for snappyHexMesh to remove and comes out as a
    dented single layer of cells rather than as a body with two faces.
    """
    if background_cell_size_m <= 0.0:
        raise ValueError(
            f"background cell size must be positive, got {background_cell_size_m}")

    import math

    for surface in surfaces:
        largest = surface.max_feature_size_m()
        if background_cell_size_m >= largest:
            raise ValueError(
                f"background_cell_size_m ({background_cell_size_m}) is not smaller "
                f"than the largest dimension of surface {surface.name!r} "
                f"({largest:.6g} m), so the whole body can sit inside one background "
                f"cell and never be found. Reduce the background cell size."
            )

        smallest = surface.min_feature_size_m()
        refined = surface.refined_cell_size_m(background_cell_size_m)
        needed = smallest / MIN_CELLS_ACROSS_THINNEST_FEATURE
        if refined > needed:
            required_level = math.ceil(math.log2(background_cell_size_m / needed))
            raise ValueError(
                f"surface {surface.name!r} at refinement level {surface.level} gives "
                f"cells of {refined:.6g} m, but its thinnest dimension is "
                f"{smallest:.6g} m -- only {smallest / refined:.2f} cells across, "
                f"against the {MIN_CELLS_ACROSS_THINNEST_FEATURE} needed to mesh it "
                f"as a solid. Raise its refinement level to {required_level}, or "
                f"reduce background_cell_size_m."
            )


def render_snap_controls() -> list[str]:
    """``snapControls``, tuned for analytic primitives with no feature edges.

    Feature snapping is off. The primitives here have no feature edges to capture
    except where a surface meets a domain boundary, and explicit feature snapping
    tends to pull points *off* such a surface rather than onto it. The one place
    it would matter -- the rim where the inflow hemisphere crosses ``x = 0`` -- is
    a right-angle crossing, the well-conditioned case.
    """
    return [
        "snapControls",
        "{",
        "    nSmoothPatch    3;",
        "    tolerance       2.0;",
        "    nSolveIter      50;",
        "    nRelaxIter      5;",
        "    nFeatureSnapIter        10;",
        "    implicitFeatureSnap     false;",
        "    explicitFeatureSnap     false;",
        "    multiRegionFeatureSnap  false;",
        "}",
    ]


def render_add_layers_controls() -> list[str]:
    """``addLayersControls``. Present but inert -- DSMC needs no prism layers.

    A DSMC wall interaction is a discrete particle-surface collision, not a
    resolved viscous sublayer, so there is nothing for a layer stack to resolve.
    The block is still written because snappyHexMesh requires the entry even when
    ``addLayers`` is false.
    """
    return [
        "addLayersControls",
        "{",
        "    relativeSizes       true;",
        "    layers {}",
        "    expansionRatio      1.0;",
        "    finalLayerThickness 0.3;",
        "    minThickness        0.1;",
        "    nGrow               0;",
        "    featureAngle        60;",
        "    nRelaxIter          3;",
        "    nSmoothSurfaceNormals 1;",
        "    nSmoothNormals      3;",
        "    nSmoothThickness    10;",
        "    maxFaceThicknessRatio 0.5;",
        "    maxThicknessToMedialRatio 0.3;",
        "    minMedialAxisAngle  90;",
        "    nBufferCellsNoExtrude 0;",
        "    nLayerIter          50;",
        "}",
    ]


def render_snappy_dict(surfaces, *, location_in_mesh, n_cells_between_levels: int,
                       generator: str, note: str, preamble: list[str] | None = None,
                       max_global_cells: int = 20_000_000,
                       resolve_feature_angle: int = 30) -> str:
    """A complete ``snappyHexMeshDict`` for a list of searchable surfaces.

    Args:
        surfaces: the :class:`SearchableSurface` entries to carve. Each becomes
            both a ``geometry`` entry and a ``refinementSurfaces`` entry, and
            snappyHexMesh names the patch it creates after the entry.
        location_in_mesh: ``(x, y, z)`` seed point [m], which must be in the fluid.
        n_cells_between_levels: buffer cells between refinement levels.
        generator: dotted module path, for the provenance comment.
        note: one line describing the mesh.
        preamble: extra comment lines placed before the ``geometry`` block.
        max_global_cells: castellation cell ceiling. Deliberately generous: an
            octree that hits this limit stops refining and produces a *quietly
            under-resolved* mesh rather than an error, so the ceiling should be a
            backstop against a runaway configuration, not a budget.
        resolve_feature_angle: castellation feature angle [deg].

    Returns:
        The dictionary text.

    Raises:
        ValueError: for ``n_cells_between_levels < 0``, or from
            :func:`render_geometry_block` for a duplicate or degenerate surface.

    Layer addition is off. A DSMC wall interaction is a discrete particle-surface
    collision, so there is no viscous sublayer for a prism stack to resolve, and
    the highly non-orthogonal cells a layer stack produces would only hurt.
    """
    if int(n_cells_between_levels) < 0:
        raise ValueError(
            f"n_cells_between_levels must be >= 0, got {n_cells_between_levels}")

    lines = header("snappyHexMeshDict", generator, note)
    lines += [
        "castellatedMesh true;",
        "snap            true;",
        "addLayers       false;   // DSMC: no boundary-layer stack needed",
        "",
    ]
    lines += list(preamble or [])
    lines += render_geometry_block(surfaces)
    lines += [
        "",
        "castellatedMeshControls",
        "{",
        f"    maxLocalCells       {max_global_cells // 2};",
        f"    maxGlobalCells      {max_global_cells};",
        "    minRefinementCells  10;",
        "    maxLoadUnbalance    0.10;",
        f"    nCellsBetweenLevels {int(n_cells_between_levels)};",
        "",
        "    // No feature edges: an analytic sphere, cylinder or box exposes none",
        "    // that snappyHexMesh can extract without a surfaceFeatures pass.",
        "    features ();",
        "",
    ]
    lines += render_refinement_surfaces_block(surfaces, indent="    ")
    lines += [
        "",
        f"    resolveFeatureAngle {int(resolve_feature_angle)};",
        "",
        "    // No wake, shock or gap refinement regions yet -- deliberately. This",
        "    // block is the clean place to add them.",
        "    refinementRegions",
        "    {",
        "    }",
        "",
        "    // In the fluid: inside the box, outside every carved body, and off",
        "    // every symmetry plane. snappyHexMesh keeps the region connected to",
        "    // this point and discards everything else.",
        f"    locationInMesh {fmt_point(location_in_mesh)};",
        "",
        "    allowFreeStandingZoneFaces true;",
        "}",
        "",
    ]
    lines += render_snap_controls()
    lines += [""]
    lines += render_add_layers_controls()
    lines += [
        "",
        "meshQualityControls",
        "{",
        '    #include "meshQualityDict"',
        "}",
        "",
        "debug 0;",
        "mergeTolerance 1e-6;",
        "",
        "// ************************************************************************* //",
    ]
    return "\n".join(lines) + "\n"


def render_mesh_quality_dict(generator: str) -> str:
    """``meshQualityDict``, ``#include``d by ``snappyHexMeshDict``.

    Kept as a local file rather than including OpenFOAM's own
    ``etc/caseDicts/meshQualityDict`` so a case does not depend on an installation
    path that varies between distributions and versions.
    """
    lines = header("meshQualityDict", generator, "Quality limits for snappyHexMesh.")
    lines += [
        "maxNonOrtho         65;",
        "maxBoundarySkewness 20;",
        "maxInternalSkewness  4;",
        "maxConcave          80;",
        "minVol              1e-13;",
        "minTetQuality       1e-30;",
        "minArea             -1;",
        "minTwist            0.02;",
        "minDeterminant      0.001;",
        "minFaceWeight       0.02;",
        "minVolRatio         0.01;",
        "minTriangleTwist    -1;",
        "",
        "nSmoothScale 4;",
        "errorReduction 0.75;",
        "",
        "relaxed",
        "{",
        "    maxNonOrtho 75;",
        "}",
        "",
        "// ************************************************************************* //",
    ]
    return "\n".join(lines) + "\n"


# --------------------------------------------------------------------------- #
# the background box
# --------------------------------------------------------------------------- #

@dataclass(frozen=True)
class BoxPatch:
    """One boundary patch of the background box.

    Attributes:
        name: patch name.
        type: OpenFOAM geometric type -- ``patch``, ``wall`` or ``symmetry``.
        faces: which box faces belong to it; keys of :data:`BOX_FACES`.
        comment: appended to the patch entry, for a reader of the dictionary.
    """

    name: str
    type: str
    faces: tuple
    comment: str = ""


def render_box_block_mesh_dict(bounds, divisions, patches, *, generator: str,
                               note: str) -> str:
    """A plain uniform hexahedral box, with named boundary patches.

    Args:
        bounds: ``(x_min, x_max, y_min, y_max, z_min, z_max)`` [m].
        divisions: ``(nx, ny, nz)`` cell counts along ``x``, ``y`` and ``z``.
        patches: :class:`BoxPatch` entries. Every face in :data:`BOX_FACES` must
            be claimed exactly once.
        generator: dotted module path, for the provenance comment.
        note: one line describing the mesh.

    Returns:
        The dictionary text.

    Raises:
        ValueError: for inverted bounds, non-positive divisions, an unknown face
            key, or a face claimed twice or not at all. A box with an unclaimed
            face is not a closed domain, and blockMesh's default patch would
            silently absorb it.
    """
    x_min, x_max, y_min, y_max, z_min, z_max = (float(v) for v in bounds)
    for axis, (lo, hi) in zip("xyz", ((x_min, x_max), (y_min, y_max), (z_min, z_max))):
        if not hi > lo:
            raise ValueError(f"{axis} bounds are inverted or empty: {lo} .. {hi}")

    nx, ny, nz = (int(v) for v in divisions)
    if min(nx, ny, nz) < 1:
        raise ValueError(f"cell divisions must be >= 1, got {(nx, ny, nz)}")

    claimed: dict[str, str] = {}
    for patch in patches:
        for key in patch.faces:
            if key not in BOX_FACES:
                raise ValueError(
                    f"patch {patch.name!r}: unknown box face {key!r}; "
                    f"valid: {sorted(BOX_FACES)}")
            if key in claimed:
                raise ValueError(
                    f"box face {key!r} is claimed by both {claimed[key]!r} and "
                    f"{patch.name!r}")
            claimed[key] = patch.name
    missing = sorted(set(BOX_FACES) - set(claimed))
    if missing:
        raise ValueError(
            f"box faces {missing} are not assigned to any patch; the domain would "
            f"not be closed")

    # Canonical OpenFOAM ordering: local x1 = +x, x2 = +y, x3 = +z, so the
    # (nx ny nz) triple is applied to the axes its name implies.
    verts = [
        (x_min, y_min, z_min), (x_max, y_min, z_min),
        (x_max, y_max, z_min), (x_min, y_max, z_min),
        (x_min, y_min, z_max), (x_max, y_min, z_max),
        (x_max, y_max, z_max), (x_min, y_max, z_max),
    ]

    lines = header("blockMeshDict", generator, note)
    lines += ["scale   1;", "", "vertices", "("]
    lines += [f"    {fmt_point(v)}" for v in verts]
    lines += [
        ");",
        "",
        "blocks",
        "(",
        f"    hex (0 1 2 3 4 5 6 7) ({nx} {ny} {nz}) simpleGrading (1 1 1)",
        ");",
        "",
        "// No curved edges: every curved surface is introduced by snappyHexMesh.",
        "edges",
        "(",
        ");",
        "",
        "boundary",
        "(",
    ]
    for patch in patches:
        lines += [f"    {patch.name}", "    {", f"        type {patch.type};"]
        if patch.comment:
            lines.append(f"        // {patch.comment}")
        lines += ["        faces", "        ("]
        for key in patch.faces:
            a, b, c, d = BOX_FACES[key]
            lines.append(f"            ({a} {b} {c} {d})   // {key}")
        lines += ["        );", "    }", ""]
    lines += [
        ");",
        "",
        "mergePatchPairs",
        "(",
        ");",
        "",
        "// ************************************************************************* //",
    ]
    return "\n".join(lines) + "\n"


def uniform_divisions(bounds, cell_size_m: float) -> tuple[int, int, int]:
    """Cell counts giving cells as close to cubic as rounding allows.

    Args:
        bounds: ``(x_min, x_max, y_min, y_max, z_min, z_max)`` [m].
        cell_size_m: target background cell size [m].

    Returns:
        ``(nx, ny, nz)``, each at least 1.

    snappyHexMesh's octree halves a cell in all three directions at once, so a
    background cell that is not roughly cubic stays not-roughly-cubic at every
    refinement level. Rounding to the nearest count per axis keeps the aspect
    ratio within one rounding step of 1.
    """
    if cell_size_m <= 0.0:
        raise ValueError(f"cell size must be positive, got {cell_size_m}")
    x_min, x_max, y_min, y_max, z_min, z_max = (float(v) for v in bounds)
    return (
        max(1, round((x_max - x_min) / cell_size_m)),
        max(1, round((y_max - y_min) / cell_size_m)),
        max(1, round((z_max - z_min) / cell_size_m)),
    )
