r"""Generate a snappyHexMesh setup for the box-with-hemispherical-cavity geometry.

An alternative to the projected O-grid in :mod:`plumetools.foamio.blockmesh`,
selected by ``mesh.type: snappy_hex_sphere``.

The sphere is declared as a ``searchableSphere`` **primitive**, so no STL is
needed and the surface is analytic: snappyHexMesh snaps to the true sphere rather
than to a triangulation of it.

Three files are written:

    system/blockMeshDict      a plain graded box -- the background mesh
    system/snappyHexMeshDict  the searchableSphere and the castellate/snap controls
    system/meshQualityDict    quality limits, #included by the above

and the pipeline is::

    blockMesh                 # background box
    snappyHexMesh -overwrite  # carve the cavity, snap to the sphere

How the cavity appears
----------------------
The sphere is centred at the origin, which lies **on** the ``x = 0`` face of the
background box (``x in [0, L]``). Only the ``+x`` half of the sphere therefore
intersects the mesh, and that is what gets carved out -- the hemisphere falls out
of the geometry rather than needing to be constructed. ``locationInMesh`` is
placed in the fluid, outside the sphere, so snappyHexMesh keeps the region
connected to it and discards the cavity interior.

Trade-off against the projected O-grid
--------------------------------------
The projected O-grid (``mesh.type: block_mesh_ogrid`` with
``mesh.projection: searchable_sphere``) gives an exact sphere, a pure hexahedral
mesh, a face count of exactly ``5*n^2``, and a structured radial grading. Prefer
it unless something rules it out.

snappyHexMesh instead gives:

* **Polyhedral cells and polygonal faces near the surface.** Castellation splits
  hexes and snapping produces faces with more than four vertices.
  :func:`plumetools.geometry.centroid` divides by ``len(vertices)`` so it handles
  those correctly -- but the legacy ``/3.0`` divisor would be wrong on every one
  of them (finding AR-01).
* **An unpredictable inflow face count**, set by refinement level and snapping
  rather than by a formula. Comparisons against the 2044-face Pointwise mesh stop
  being like-for-like.
* **Approximate radii.** Snapped points land on the sphere to within the snapping
  tolerance, not exactly. :mod:`plumetools.verify_mesh` loosens its radius check
  accordingly for this mesh type.
* **A tangency risk.** The sphere meets ``x = 0`` tangentially, and snappyHexMesh
  is at its least reliable where a surface grazes a domain boundary. Inspect the
  resulting ``sym`` / ``inflow`` intersection before trusting it.
"""

from __future__ import annotations

from pathlib import Path

BANNER = """\
/*--------------------------------*- C++ -*----------------------------------*\\
| =========                 |                                                 |
| \\\\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox           |
|  \\\\    /   O peration     | Version:  v1706                                 |
|   \\\\  /    A nd           | Web:      www.OpenFOAM.com                      |
|    \\\\/     M anipulation  |                                                 |
\\*---------------------------------------------------------------------------*/"""

SEPARATOR = "// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //"


def _fmt(v: float) -> str:
    return f"{v:.10g}"


def _header(object_name: str, note: str) -> list[str]:
    return [
        BANNER,
        "// GENERATED by plumetools.foamio.snappy from case.yaml -- do not edit.",
        "// Regenerate with ./Allmesh. See docs/mesh.md.",
        f"// {note}",
        "FoamFile",
        "{",
        "    version     2.0;",
        "    format      ascii;",
        "    class       dictionary;",
        f"    object      {object_name};",
        "}",
        SEPARATOR,
        "",
    ]


def _write(path: Path, lines: list[str]) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines) + "\n")
    return path


def _geometry(cfg) -> tuple[float, float, float]:
    m = cfg.mesh
    R, H, L = float(m.sphere_radius_m), float(m.box_half_width_m), float(m.box_length_m)
    if not 0 < R < H:
        raise ValueError(f"need 0 < sphere_radius_m ({R}) < box_half_width_m ({H})")
    if L <= R:
        raise ValueError(f"need box_length_m ({L}) > sphere_radius_m ({R})")
    return R, H, L


def background_divisions(cfg) -> tuple[int, int, int]:
    """Background cell counts from ``mesh.background_cell_size_m``.

    Returns ``(nx, ny, nz)``, each at least 1. Cells are kept as close to cubic as
    rounding allows, which is what snappyHexMesh's octree refinement assumes.
    """
    R, H, L = _geometry(cfg)
    size = float(cfg.mesh.background_cell_size_m)
    if size <= 0:
        raise ValueError(f"background_cell_size_m must be positive, got {size}")
    if size > R:
        raise ValueError(
            f"background_cell_size_m ({size}) exceeds the sphere radius ({R}); the "
            f"cavity would fall between cells. Use at most R/4."
        )
    return (max(1, round(L / size)),
            max(1, round(2 * H / size)),
            max(1, round(2 * H / size)))


def location_in_mesh(cfg) -> tuple[float, float, float]:
    """A point in the fluid: inside the box, outside the sphere.

    Deliberately off-axis and off any symmetry plane. A ``locationInMesh`` sitting
    exactly on a face, edge, or plane of symmetry is a classic way to make
    snappyHexMesh keep the wrong region or fail outright.
    """
    _R, H, L = _geometry(cfg)
    return (0.5 * L, 0.31 * H, 0.27 * H)


def render_background_block_mesh_dict(cfg) -> str:
    """A plain graded box for snappyHexMesh to refine.

    Patches: ``sym`` on ``x = 0``, ``vacuum`` on the other five faces. The
    ``inflow`` patch does not exist yet -- snappyHexMesh creates it when it carves
    the cavity.
    """
    R, H, L = _geometry(cfg)
    nx, ny, nz = background_divisions(cfg)
    names = cfg.mesh.patch_names
    p_outer = names.get("outer", "vacuum")
    p_sym = names.get("symmetry", "sym")

    # Box corners: 0-3 at x = 0, 4-7 at x = L, both wound (-y-z, +y-z, +y+z, -y+z).
    verts = [
        (0.0, -H, -H), (0.0, H, -H), (0.0, H, H), (0.0, -H, H),
        (L, -H, -H), (L, H, -H), (L, H, H), (L, -H, H),
    ]

    lines = _header(
        "blockMeshDict",
        f"Background box for snappyHexMesh: {nx}x{ny}x{nz} = {nx * ny * nz} cells, "
        f"cell size ~{_fmt(L / nx)} m.",
    )
    lines += ["scale   1;", "", "vertices", "("]
    lines += [f"    ({_fmt(x)} {_fmt(y)} {_fmt(z)})" for x, y, z in verts]
    lines += [
        ");",
        "",
        "blocks",
        "(",
        f"    hex (0 1 2 3 4 5 6 7) ({nx} {ny} {nz}) simpleGrading (1 1 1)",
        ");",
        "",
        "// No curved edges: the sphere is introduced by snappyHexMesh, not here.",
        "edges",
        "(",
        ");",
        "",
        "boundary",
        "(",
        f"    {p_sym}",
        "    {",
        "        type symmetry;",
        "        // x = 0. snappyHexMesh will cut the hemisphere out of this face.",
        "        faces",
        "        (",
        "            (0 3 2 1)",
        "        );",
        "    }",
        "",
        f"    {p_outer}",
        "    {",
        "        type patch;",
        "        // the remaining five box faces",
        "        faces",
        "        (",
        "            (4 5 6 7)   // x = L",
        "            (0 1 5 4)   // z = -H",
        "            (3 7 6 2)   // z = +H",
        "            (0 4 7 3)   // y = -H",
        "            (1 2 6 5)   // y = +H",
        "        );",
        "    }",
        "",
        ");",
        "",
        "mergePatchPairs",
        "(",
        ");",
        "",
        "// ************************************************************************* //",
    ]
    return "\n".join(lines) + "\n"


def render_snappy_hex_mesh_dict(cfg) -> str:
    """The searchableSphere primitive plus castellate and snap controls."""
    R, H, L = _geometry(cfg)
    m = cfg.mesh
    level = int(m.refinement_level)
    if level < 0:
        raise ValueError(f"refinement_level must be >= 0, got {level}")
    inflow = m.patch_names.get("inflow", "inflow")
    lx, ly, lz = location_in_mesh(cfg)
    _nx, _ny, _nz = background_divisions(cfg)
    finest = (L / _nx) / (2 ** level)

    lines = _header(
        "snappyHexMeshDict",
        f"Carve a hemispherical cavity of radius {_fmt(R)} m out of the background box. "
        f"Refinement level {level} -> ~{_fmt(finest)} m at the surface.",
    )
    lines += [
        "castellatedMesh true;",
        "snap            true;",
        "addLayers       false;   // DSMC: no boundary-layer stack needed",
        "",
        "// The inflow surface as an analytic primitive -- no STL, so snapping targets",
        "// the true sphere rather than a triangulation of it. The geometry entry name",
        f"// becomes the patch name, which is why it is '{inflow}'.",
        "geometry",
        "{",
        f"    {inflow}",
        "    {",
        "        type    searchableSphere;",
        f"        centre  ({_fmt(0.0)} {_fmt(0.0)} {_fmt(0.0)});",
        f"        radius  {_fmt(R)};",
        "        // v1706 spells this 'centre'; OpenFOAM v2006+ also accepts 'origin'.",
        "    }",
        "}",
        "",
        "castellatedMeshControls",
        "{",
        "    maxLocalCells       2000000;",
        "    maxGlobalCells      4000000;",
        "    minRefinementCells  10;",
        "    maxLoadUnbalance    0.10;",
        f"    nCellsBetweenLevels {int(m.n_cells_between_levels)};",
        "",
        "    // No feature edges: a sphere has none.",
        "    features ();",
        "",
        "    refinementSurfaces",
        "    {",
        f"        {inflow}",
        "        {",
        f"            level ({level} {level});",
        "            patchInfo",
        "            {",
        "                type patch;   // never 'wall': this is an inflow, and it must",
        "                              // not become a no-slip surface by default",
        "            }",
        "        }",
        "    }",
        "",
        "    resolveFeatureAngle 30;",
        "",
        "    refinementRegions",
        "    {",
        "    }",
        "",
        "    // In the fluid: inside the box, outside the sphere, and deliberately off",
        "    // every symmetry plane. snappyHexMesh keeps the region connected to this",
        "    // point and discards the cavity interior.",
        f"    locationInMesh ({_fmt(lx)} {_fmt(ly)} {_fmt(lz)});",
        "",
        "    allowFreeStandingZoneFaces true;",
        "}",
        "",
        "snapControls",
        "{",
        "    nSmoothPatch    3;",
        "    tolerance       2.0;",
        "    nSolveIter      50;",
        "    nRelaxIter      5;",
        "    // Feature snapping is off: a sphere has no feature edges to capture, and",
        "    // enabling it near the x = 0 tangency tends to pull points off the surface.",
        "    nFeatureSnapIter        10;",
        "    implicitFeatureSnap     false;",
        "    explicitFeatureSnap     false;",
        "    multiRegionFeatureSnap  false;",
        "}",
        "",
        "addLayersControls",
        "{",
        "    relativeSizes       true;",
        "    layers {}",
        "    expansionRatio      1.0;",
        "    finalLayerThickness 0.3;",
        "    minThickness        0.1;",
        "    nGrow               0;",
        "    featureAngle        60;",
        "    nRelaxIter          3;",
        "    nSmoothSurfaceNormals 1;",
        "    nSmoothNormals      3;",
        "    nSmoothThickness    10;",
        "    maxFaceThicknessRatio 0.5;",
        "    maxThicknessToMedialRatio 0.3;",
        "    minMedialAxisAngle  90;",
        "    nBufferCellsNoExtrude 0;",
        "    nLayerIter          50;",
        "}",
        "",
        "meshQualityControls",
        "{",
        '    #include "meshQualityDict"',
        "}",
        "",
        "debug 0;",
        "mergeTolerance 1e-6;",
        "",
        "// ************************************************************************* //",
    ]
    return "\n".join(lines) + "\n"


def render_mesh_quality_dict(cfg) -> str:
    """Quality limits, ``#include``d by snappyHexMeshDict.

    Kept as a local file rather than including OpenFOAM's
    ``etc/caseDicts/meshQualityDict`` so the case does not depend on an
    installation path.
    """
    lines = _header("meshQualityDict", "Quality limits for snappyHexMesh.")
    lines += [
        "maxNonOrtho         65;",
        "maxBoundarySkewness 20;",
        "maxInternalSkewness  4;",
        "maxConcave          80;",
        "minVol              1e-13;",
        "minTetQuality       1e-30;",
        "minArea             -1;",
        "minTwist            0.02;",
        "minDeterminant      0.001;",
        "minFaceWeight       0.02;",
        "minVolRatio         0.01;",
        "minTriangleTwist    -1;",
        "",
        "nSmoothScale 4;",
        "errorReduction 0.75;",
        "",
        "relaxed",
        "{",
        "    maxNonOrtho 75;",
        "}",
        "",
        "// ************************************************************************* //",
    ]
    return "\n".join(lines) + "\n"


def write_snappy_setup(case_dir: Path, cfg) -> list[Path]:
    """Write all three dictionaries for the snappyHexMesh path.

    Args:
        case_dir: an OpenFOAM case directory.
        cfg: a :class:`plumetools.config.CaseConfig` with
            ``mesh.type == "snappy_hex_sphere"``.

    Returns:
        The paths written, in the order blockMesh / snappyHexMesh consume them.
    """
    if cfg.mesh.type != "snappy_hex_sphere":
        raise ValueError(
            f"write_snappy_setup needs mesh.type 'snappy_hex_sphere', "
            f"got {cfg.mesh.type!r}"
        )
    case_dir = Path(case_dir)
    system = case_dir / "system"
    return [
        _write(system / "blockMeshDict", render_background_block_mesh_dict(cfg).splitlines()),
        _write(system / "snappyHexMeshDict", render_snappy_hex_mesh_dict(cfg).splitlines()),
        _write(system / "meshQualityDict", render_mesh_quality_dict(cfg).splitlines()),
    ]
